spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092


#Add review-service as a dependency in other modules (e.g., api-gateway, bff-service).
#
#In pom.xml of other modules:
#<dependency>
#    <groupId>com.example</groupId>
#    <artifactId>review-service</artifactId>
#    <version>${project.version}</version>
#</dependency>

#Use Feign clients or RestTemplate in other modules to interact with review-service endpoints.
#
#Example Feign client in bff-service:
#
#java
#Copy code
#@FeignClient(name = "review-service")
#public interface ReviewClient {
#    @PostMapping("/reviews")
#    Review addReview(@RequestBody Review review);
#
#    @PutMapping("/reviews/{id}/moderate")
#    void moderateReview(@PathVariable("id") Long id, @RequestParam boolean approve);
#}


#Example usage in a service:
#
#java
#Copy code
#@Service
#public class CourseService {
#    @Autowired
#    private ReviewClient reviewClient;
#
#    public void addReview(Review review) {
#        reviewClient.addReview(review);
#    }
#
#    public void moderateReview(Long id, boolean approve) {
#        reviewClient.moderateReview(id, approve);
#    }
#}

#Register the review-service module with the service-registry for service discovery.
#
#3. Kafka Integration (if needed)
#Add Kafka dependencies to review-service.l